
# TRAIN AND VALID DATASET LOCATION
TRAIN_IMG_DIR: 'lsvrc_2014/ILSVRC2012_img_train/'
VALID_IMG_DIR: 'lsvrc_2014/ILSVRC2012_img_val/'


# TARGET DIRECTORY



# CAFFE STYLE TRAIN AND VALIDATION LABELS
TRAIN_FILENAM: '../train_path.txt'
VALID_FILENAME: '../valid_path.txt'

